- name: Install and Configure Minecraft Bedrock Dedicated Server
  hosts: minecraft_servers
  vars:
    minecraft_version: 1.26.40.8
    minecraft_download_url: >-
      https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-{{ minecraft_version }}.zip
    minecraft_install_dir: /opt/minecraft_server
    minecraft_user: minecraft
    minecraft_group: minecraft
    minecraft_server_name: Nicomax Dedicated Server
    minecraft_server_port: 19132
    minecraft_max_players: 4
    minecraft_gamemode: creative
    minecraft_allow_list: false
    minecraft_difficulty: normal
    minecraft_level_name: Bedrock level
    minecraft_level_seed: Any
    server_properties: server.properties.j2

  pre_tasks:
    - name: Ensure minecraft user and group exist
      user:
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        system: "yes"

    - name: Ensure minecraft install directory exists
      file:
        path: "{{ minecraft_install_dir }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"
 
  tasks:
    - name: update apt cache
      apt:
        update_cache: "yes"

    - name: upgrade all packages to the latest version
      apt:
        upgrade: "dist"    

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip
        - curl
        
    - name: Download Minecraft Bedrock Dedicated Server
      get_url:
        url: "{{ minecraft_download_url }}"
        dest: /tmp/bedrock_server.tar.gz

    - name: Extract Minecraft Bedrock Dedicated Server
      unarchive:
        src: /tmp/bedrock_server.tar.gz
        dest: "{{ minecraft_install_dir }}"
        remote_src: "yes"
  
    - name: Set server permissions
      file:
        path: "{{ minecraft_install_dir }}"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"
     
    - name: Start Minecraft Bedrock Dedicated Server
      service:
        name: "{{ minecraft_install_dir }}/bedrock_server"
        enabled: "yes"
        state: started

    - name: Configure Minecraft Bedrock Dedicated Server
      template:
        src: server.properties.j2
        dest: "{{ minecraft_install_dir }}/server.properties"
      notify: Restart Minecraft Bedrock Dedicated Server

    - name: Configure firewall to allow SSH traffic
      ufw:
        rule: allow
        port: 22
        proto: tcp
        state: enabled  

    - name: Configure firewall to allow Minecraft Bedrock Dedicated Server traffic
      ufw:
        rule: allow
        port: "{{ minecraft_server_port }}"
        proto: udp
        state: enabled

  handlers:
    - name: Restart Minecraft Bedrock Dedicated Server
      service:
        name: "{{ minecraft_install_dir }}/bedrock_server"
        state: restarted