- name: Install and Configure Minecraft Bedrock Dedicated Server
  hosts: minecraft_servers
  vars:
    minecraft_version: 1.26.40.8
    minecraft_download_url: >-
      https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-{{ minecraft_version }}.zip
    minecraft_install_dir: /opt/minecraft_server
    minecraft_user: minecraft
    minecraft_group: minecraft
    minecraft_server_name: Nicomax Dedicated Server
    minecraft_server_port: 19132
    minecraft_max_players: 4
    minecraft_gamemode: creative
    minecraft_difficulty: normal
    minecraft_allow_cheats: true
    minecraft_allow_list: false
    minecraft_level_name: Bedrock level
    minecraft_level_seed: Any
    server_properties: server.properties.j2

  pre_tasks:
    - name: Ensure minecraft user and group exist
      user:
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        system: "yes"
        state: present

    - name: Ensure minecraft install directory exists
      file:
        path: "{{ minecraft_install_dir }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"
 
  tasks:
    - name: update apt cache
      apt:
        update_cache: "yes"

    - name: upgrade all packages to the latest version
      apt:
        upgrade: "dist"    

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip
        - curl
        
    - name: Download Minecraft Bedrock Dedicated Server
      get_url:
        url: "{{ minecraft_download_url }}"
        dest: /tmp/bedrock_server.tar.gz

    - name: Extract Minecraft Bedrock Dedicated Server
      unarchive:
        src: /tmp/bedrock_server.tar.gz
        dest: "{{ minecraft_install_dir }}"
        remote_src: "yes"
  
    - name: Set server permissions
      file:
        path: "{{ minecraft_install_dir }}"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"

    - name: Configure Minecraft Bedrock Dedicated Server
      template:
        src: server.properties.j2
        dest: "{{ minecraft_install_dir }}/server.properties"

    - name: Create systemd service for Minecraft Bedrock Dedicated Server
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Bedrock Dedicated Server
          After=network.target

          [Service]
          User={{ minecraft_user }}
          Group={{ minecraft_group }}
          WorkingDirectory={{ minecraft_install_dir }}
          ExecStart={{ minecraft_install_dir }}/bedrock_server
          Restart=on-failure
          Nice=1

          [Install]
          WantedBy=multi-user.target
    
    - name: Reload systemd daemon
      systemd:
        daemon_reload: "yes"

    - name: Start Minecraft Bedrock Dedicated Server
      service:
        name: "minecraft"
        enabled: "yes"
        state: started